### PR TITLE
Add optional block_identifier

### PR DESCRIPTION
**Pull request by 9-dorf**
Optional block_identifier allows historical data to be read.

### CODE REVIEW

**Comment by thanpolas** [comment]
that's interesting... wasn't it populated by default by the underlying library?

**Comment by 9-dorf** [comment]
Yes, but this allows users to pass in custom block numbers so you look back in time.

**Comment by thanpolas** [comment]
> Yes, but this allows users to pass in custom block numbers so you look back in time.

correct, if that's the use case then yea, this is required.

**Comment by 0rtis** [comment]
Implemented in aa12a6f

**Pull request closed without merging**
